<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Execs</name>
   <tag></tag>
   <elementGuidId>6e6599c3-9dca-4a89-a9e0-3dd119adfdfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[26]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .Board_dropzone_2vdCK > div > div > div > .Board_bottomRow_2kT33 > .Board_right_gRZqf > button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a0a131d-6a32-4694-a8e5-cabad77397cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0618f17-7902-4ddf-8046-32791a303726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Board_textBtn_3RMSM btn btn-outline-primary btn-sm</value>
      <webElementGuid>ff2fc070-04b3-4a86-89bf-5cba6fb575c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Execs</value>
      <webElementGuid>0a51512a-7f55-4376-9c6b-b6467873aa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/div[@class=&quot;Board_board_1Q2JI&quot;]/div[@class=&quot;Board_column_2B94F&quot;]/div[@class=&quot;Board_dropzone_2vdCK&quot;]/div[1]/div[@class=&quot;Board_item_3Cb76 cls-Bonds&quot;]/div[1]/div[@class=&quot;Board_bottomRow_2kT33&quot;]/div[@class=&quot;Board_right_gRZqf&quot;]/button[@class=&quot;Board_textBtn_3RMSM btn btn-outline-primary btn-sm&quot;]</value>
      <webElementGuid>5d1d13cc-bf76-4b65-81ef-102fafbf5d2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[26]</value>
      <webElementGuid>f978a089-83f0-460d-915d-0131f0eeaa37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>d97d28ab-83aa-43cf-b042-3abf0de8019a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACKED'])[1]/following::button[1]</value>
      <webElementGuid>c49d3816-089c-49de-bd50-03a6281d196d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(PYG)'])[4]/following::button[1]</value>
      <webElementGuid>ab5778c4-ac6c-4b7f-a394-9521b833be71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Ref.'])[5]/preceding::button[1]</value>
      <webElementGuid>08d449c5-2e26-4454-b74a-25fac5184dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross'])[1]/preceding::button[4]</value>
      <webElementGuid>620fb250-4101-49a2-ab65-236d1f86887f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Execs']/parent::*</value>
      <webElementGuid>7b6674e5-5ccb-47bb-94a6-c34ca3807e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>a2c9baaa-1415-49a2-a2a0-480554ee69ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Execs' or . = 'Execs')]</value>
      <webElementGuid>52759e3a-96fa-4aee-aa85-4ca73684177a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
