<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ack</name>
   <tag></tag>
   <elementGuidId>1a2fc038-3c5f-412f-a961-d2dec0db9158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.Board_textBtn_3RMSM.btn.btn-outline-primary.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Ack&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e2232acc-2fa7-43da-ac5e-0f736149b883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7f6cd8c-052b-4f50-a5f4-178950e03edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Board_textBtn_3RMSM btn btn-outline-primary btn-sm</value>
      <webElementGuid>017e8fa1-e1b2-49c6-b64d-8ddd3f977ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ack</value>
      <webElementGuid>76f8c476-b43f-49f8-9884-2fe9d812e52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/div[@class=&quot;Board_board_1Q2JI&quot;]/div[@class=&quot;Board_column_2B94F&quot;]/div[@class=&quot;Board_dropzone_2vdCK Board_customHeight_rPMbG&quot;]/div[1]/div[@class=&quot;Board_item_3Cb76 cls-Bonds&quot;]/div[1]/div[@class=&quot;Board_bottomRow_2kT33&quot;]/div[@class=&quot;Board_right_gRZqf&quot;]/button[@class=&quot;Board_textBtn_3RMSM btn btn-outline-primary btn-sm&quot;]</value>
      <webElementGuid>41c326cb-bd76-4190-931a-060a7e756244</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>9d644d89-1bd6-4bb6-8c9d-9339bfc42077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/main/div/div/div[2]/div/div[2]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>60dcb5dc-6336-4b43-8321-6d9730fb8bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ROUTED'])[1]/following::button[1]</value>
      <webElementGuid>f81e6574-4c1d-473c-9568-c6175c10b212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(PYG)'])[1]/following::button[1]</value>
      <webElementGuid>0bf54c6c-62f1-42b2-9208-6ffdb9d1a232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/preceding::button[1]</value>
      <webElementGuid>36c29072-1d49-4cc9-82b7-f618ed564400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cross Ref.'])[1]/preceding::button[2]</value>
      <webElementGuid>a52f4a69-2af7-498d-a5f8-70e606f2104e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ack']/parent::*</value>
      <webElementGuid>808a3cf9-01ba-491b-a4ee-4807fb2271ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3f5d26ed-1968-4166-9012-d0a353283214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ack' or . = 'Ack')]</value>
      <webElementGuid>c71fbfe4-6d69-4774-9f4a-d0eaca11ed6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
