<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>boton mas</name>
   <tag></tag>
   <elementGuidId>ce2e2cfd-c102-46a1-8d2b-8797c82a53cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@class,'mfb-component__button--main')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mfb-component__child-icon.fa.fa-dollar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.mfb-component__button--child >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>be2a0def-2082-4085-bf84-d24b792d79ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mfb-component__child-icon fa fa-dollar</value>
      <webElementGuid>e9912f81-ed9c-4da5-8883-f2a38187ce3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/div[@class=&quot;app-body&quot;]/main[@class=&quot;main&quot;]/div[@class=&quot;container-fluid&quot;]/div[1]/ul[@class=&quot;mfb-slidein mfb-component--br FloatingButton_root_2RALo FloatingButton_magic-reply-disabled_2582L&quot;]/li[@class=&quot;mfb-component__wrap&quot;]/ul[@class=&quot;mfb-component__list&quot;]/li[1]/a[@class=&quot;mfb-component__button--child&quot;]/i[@class=&quot;mfb-component__child-icon fa fa-dollar&quot;]</value>
      <webElementGuid>4d84b6be-b77d-4cf0-b36d-516efeef05fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div/ul/li/ul/li/a/i</value>
      <webElementGuid>5f277e8d-5e30-4066-9cfd-fd7c4931c2fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/ul/li/a/i</value>
      <webElementGuid>ecf8b53f-6c5c-4912-bee7-b8e7bfc77786</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
