<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PYCII01F5636 - CORPORACION INTERAMERICA_efa9da</name>
   <tag></tag>
   <elementGuidId>31fda88b-4eb7-4b95-9748-7237ac8d2f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='react-autowhatever-1--item-0']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Field-module_suggestionItem_2Khdh</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;PYCII01F5636 - CORPORACION INTERAMERICANA DE INVERSIONES (PYCII01&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8976d47-f716-4d80-86d3-00cb1ea921fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Field-module_suggestionItem_2Khdh</value>
      <webElementGuid>53aa758c-92e6-4544-a4d4-5979673e9ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PYCII01F5636 - CORPORACION INTERAMERICANA DE INVERSIONES (PYCII01</value>
      <webElementGuid>41b2f606-0fcd-48e7-8168-f80d07504ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-autowhatever-1--item-0&quot;)/div[@class=&quot;Field-module_suggestionItem_2Khdh&quot;]</value>
      <webElementGuid>72703361-b0e6-4c58-add6-676eda4c3078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='react-autowhatever-1--item-0']/div</value>
      <webElementGuid>f645dc75-a385-4eed-a20b-577fba6245f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Symbol'])[1]/following::div[6]</value>
      <webElementGuid>e066c74f-c379-4b0b-9d9b-dbdbd0828be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sell'])[1]/following::div[12]</value>
      <webElementGuid>ecc9ced1-d0ba-4ae1-b508-9fb6356f9d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PYCII01F5636']/parent::*</value>
      <webElementGuid>c05c2faa-2c6c-43f3-bc59-81f49a7b7fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/div</value>
      <webElementGuid>cb829d40-67b4-4f70-bbf9-9994c29a5f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PYCII01F5636 - CORPORACION INTERAMERICANA DE INVERSIONES (PYCII01' or . = 'PYCII01F5636 - CORPORACION INTERAMERICANA DE INVERSIONES (PYCII01')]</value>
      <webElementGuid>08896cbc-6b6e-4b79-9165-9fcefec94b38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
