<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_hh</name>
   <tag></tag>
   <elementGuidId>c98e8995-4571-49b4-bff6-d1813c36baf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Error, insufficient funds (Total:2018140.00 | Balance:-4040244815.00)'])[1]/following::textarea[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Message&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>579e12fa-b430-4fa4-ae26-da855a4b5d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>934a1052-266e-432d-805f-791bc50ceb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Message</value>
      <webElementGuid>3d381b14-14de-4f96-88ed-3d54ceb71330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>105929d2-da1c-4e3f-9583-91620ff00542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bcd6bfa0-8a76-4241-b168-71d10ac26a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>hh</value>
      <webElementGuid>9c60339f-4ce2-49d5-8bc3-77125b2391e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden sidebar-minimized brand-minimized modal-open&quot;]/div[3]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog Order-module_modal_3GIJB&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;Order-module_body_2A9Fp modal-body&quot;]/div[@class=&quot;Precheck-module_precheck_35KLp&quot;]/div[@class=&quot;Precheck-module_authorizations_2WUl3&quot;]/div[@class=&quot;Precheck-module_authorization_34TJM&quot;]/div[@class=&quot;Field-module_field_1_UDZ form-group&quot;]/textarea[@class=&quot;form-control&quot;]</value>
      <webElementGuid>d8d41ee4-33b7-40cd-9e22-bf2a34de96c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error, insufficient funds (Total:2018140.00 | Balance:-4040244815.00)'])[1]/following::textarea[1]</value>
      <webElementGuid>f984f052-aad6-4734-b55d-a1643d3061e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[1]/following::textarea[1]</value>
      <webElementGuid>c7198371-8350-4958-9d5f-8c011efa06d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8ba65958-e7a9-4bb2-8b65-6bf46fcf33ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[77]/preceding::textarea[1]</value>
      <webElementGuid>8a1e3a65-b95b-4f19-a24f-1e7366b28556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='hh']/parent::*</value>
      <webElementGuid>7f9cda20-9fb0-4503-9980-ee5aacb726a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>894bf9b9-f241-4e50-8122-8f8609317ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Message' and (text() = 'hh' or . = 'hh')]</value>
      <webElementGuid>6996d8b5-2d1e-4f6c-a597-f8dc5c77cf91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
