<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Authorizations_icon-bell</name>
   <tag></tag>
   <elementGuidId>27032535-b3f0-44b7-9568-476237416ba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/ul/li[2]/a/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-bell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;0AuthorizationsNo AuthorizationsView all authorizations&quot;i >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fbb798b8-76bb-40ea-ba33-6e2e511520b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-bell</value>
      <webElementGuid>61d3d8ae-0811-40b6-9982-b608af28586a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/header[@class=&quot;app-header navbar&quot;]/ul[@class=&quot;ml-auto navbar-nav&quot;]/li[@class=&quot;dropdown nav-item&quot;]/a[@class=&quot;nav-link&quot;]/span[1]/i[@class=&quot;icon-bell&quot;]</value>
      <webElementGuid>a6befa8e-7835-4117-bef9-70dfba2ea424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/ul/li[2]/a/span/i</value>
      <webElementGuid>f0b0176b-476e-47ab-b3d1-975fb2f8a12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>b46beb8d-9db8-4d68-9867-8e8a98b200c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
