<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Error, insufficient funds (Total2018140.0_31c818</name>
   <tag></tag>
   <elementGuidId>8ce8d37c-3bdb-4fa0-a045-7aa5be7b9c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/ul/li[2]/div/div/div[3]/div[2]/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Error, insufficient funds (Total:2018140.00 | Balance:-4040244815.00)Bond Buy 2.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e5f4ca16-a135-4abb-8837-9e9be12c4e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Error, insufficient funds (Total:2018140.00 | Balance:-4040244815.00)Bond Buy 2. PYCII01F5636  Cuenta 845/ Account Number: 845 QTY: 2. Currency: PYG Total:         2,018,140.00Notes:Notes:</value>
      <webElementGuid>2cffac5d-3d32-4323-8e43-31329a95794e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app&quot;]/header[@class=&quot;app-header navbar&quot;]/ul[@class=&quot;ml-auto navbar-nav&quot;]/li[@class=&quot;dropdown show nav-item&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-right show&quot;]/div[@class=&quot;style-module_container_3OsFj&quot;]/div[@class=&quot;style-module_item_2MZIx dropdown-item&quot;]/div[@class=&quot;style-module_body_1Hxwq&quot;]/p[2]</value>
      <webElementGuid>332be6dd-706a-4d34-a453-579c26a90aaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/ul/li[2]/div/div/div[3]/div[2]/p[2]</value>
      <webElementGuid>35b73f12-aa98-4f17-85ab-79179e848c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(15)'])[1]/following::p[2]</value>
      <webElementGuid>195154be-89dd-454c-9e39-c10f986f03b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>165b122f-139a-4ace-98d6-02b6202c8457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Error, insufficient funds (Total:2018140.00 | Balance:-4040244815.00)Bond Buy 2. PYCII01F5636  Cuenta 845/ Account Number: 845 QTY: 2. Currency: PYG Total:         2,018,140.00Notes:Notes:' or . = 'Error, insufficient funds (Total:2018140.00 | Balance:-4040244815.00)Bond Buy 2. PYCII01F5636  Cuenta 845/ Account Number: 845 QTY: 2. Currency: PYG Total:         2,018,140.00Notes:Notes:')]</value>
      <webElementGuid>2d872609-28f6-4a6c-a1c4-a66f937f4a4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
